name: Deploy to Tea
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tea CLI
        run: |
          curl -fsSL https://tea.xyz/install.sh | sh
          echo "$HOME/.tea/tea.xyz/bin" >> $GITHUB_PATH
          source ~/.bashrc
          
      - name: Debug Info
        run: |
          echo "PATH: $PATH"
          which tea
          tea --version
          
      - name: Prepare Package
        run: |
          # Pastikan file tea.yml valid
          cat tea.yml
          [ -f tea.yml ] || exit 1
          
      - name: Publish
        run: |
          tea publish --verbose
        env:
          TEA_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
