name: Publish to Tea
on: [push]  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - uses: teaxyz/setup-tea@v1  
      - run: tea publish  
        env:
          TEA_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
