name: Publish to Tea
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tea CLI
        run: |
          curl -fsS https://tea.xyz | sh
          echo "$HOME/.tea/tea.xyz/bin" >> $GITHUB_PATH
      - name: Publish Package
        run: tea publish
        env:
          TEA_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
